services:
  parking-monitor:
    build: .
    image: parking-monitor:latest
    container_name: parking-monitor
    ports:
      - "9878:9878"
    volumes:
      - ./config:/app/config
    environment:
      - UFP_PASSWORD=${UFP_PASSWORD}
    restart: unless-stopped
